### PR TITLE
Added two new cmdlets, incremented ModuleVersion

### PR DESCRIPTION
**Pull request by RCormier-MSFT**
Added cmdlet to return/display all checked out files
Added cmdlet to check in all checked out files (useful for migrations to Office 365)
Removed refernce to invalid cmdlet
Incremented to ModuleVersion 1.0.0..2

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/pfe/21)

### CODE REVIEW

**Comment by NikCharlebois** [comment]
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[PowerShell/Modules/PFE-SharePoint/PFE-SharePoint.psd1, line 21 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7Z9Qc56klD894YAdBG:-L7Z9Qc56klD894YAdBH:be3k95e) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/PFE-SharePoint.psd1#L21)):*
> ```PowerShell
> 		       "Cmdlets\Get-RegistryCredential\Get-RegistryCredential.psm1",
>            "Cmdlets\New-RegistryCredential\New-RegistryCredential.psm1",
>            "Cmdlets\Get-CheckedOutFilesInList\Get-CheckedOutFilesInList.psm1"
> ```

[Picky] Try keeping the tabulation aligned;

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 2 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7Z9qretUpO8hlwjMM-:-L7Z9qretUpO8hlwjMM0:b-43srub) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L2)):*
> ```PowerShell
> 
> <#PSScriptInfo
> ```

We should not have a PSScriptInfo block in modules. We should however standardize a comment template at the top of each cmdlet to standardize information about company, description and author. How about something as simple as the following?
<#
        Author:        Roger Cormier
        Company:   Microsoft
       Description: This cmdlet does abcd….
#>

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 44 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZC02b0kBO5SMQyEpO:-L7ZC02b0kBO5SMQyEpP:b-136gsv) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L44)):*
> ```PowerShell
>     [CmdletBinding()]
>     param(
>     #SPList Pipebind
> ```

Instead of adding information in comments, how about we use the HelpMessage attribute?
[parameter(HelpMessage="Represents the SPListBinding", Mandatory=$true,ValueFromPipeline=$True, ValueFromPipelineByPropertyName, ParameterSetName="ListFromPipeline", position=0))]

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 50 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZCkWgoaUX1hSqUMan:-L7ZCkWgoaUX1hSqUMao:bujzllc) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L50)):*
> ```PowerShell
>     )
> 
>     Begin
> ```

We may want to remove the Begin block since we are not initializing anything in it. Alternatively, we may want to do an additional check to ensure the piped SPList is not null and throw an error if it is.

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 51 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZCkM_PwGbb-OTY8mh:-L7ZCkM_PwGbb-OTY8mi:b1htc0x) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L51)):*
> Begin
>     {
>  
>     }
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     Process
>     {
>         $CheckedOutFiles = @{}
>         Write-Verbose "Getting checked out files"
</details>
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         foreach( $File in ($List.Items | Where-Object { $_.file.checkoutstatus -ne "None"}))
>         {
>             $CheckedOutFiles.Add($File.url, $File)
>         }
</details>
>  
>     }
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>     End
>     {
>         Return $CheckedOutFiles
>     }</details>


---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 2 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZCxwuVkSQH8exENb7:-L7ZCxwuVkSQH8exENb8:b2nreh6) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L2)):*
> ```PowerShell
> 
> <#PSScriptInfo
> ```

Same as above.

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 44 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZDSYInif81EPANOly:-L7ZDSYInif81EPANOlz:b1tdqur) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L44)):*
> ```PowerShell
> [CmdletBinding()]
> param(
> [Parameter (Mandatory=$True, ValueFromPipeline=$True, ValueFromPipelineByPropertyName=$True)]
> ```

Use HelpMessage to provide additional info on what this does.

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 47 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZDL_9K0ywsall7Vdr:-L7ZDL_9K0ywsall7Vds:b-9ks33k) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L47)):*
> ```PowerShell
> [Alias ('URL')]
> [String[]]$Site,
> [Parameter (Mandatory=$False)]
> ```

Again, provide HelpMessage to detail what this param is for.

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 75 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZDnabh01-z7-tTEwx:-L7ZDnacvyN0k_wB6KzG:bpdmknw) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L75)):*
> ```PowerShell
>                 try
>                 {
>                 $list.GetItemById(
> ```

[Picky] Ensure proper tabulation

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 87 at r1](https://reviewable.io:443/reviews/microsoft/pfe/21#-L7ZDthXFRvZUPA9_U5x:-L7ZDthXFRvZUPA9_U5y:blpme5o) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L87)):*
> ```PowerShell
>         $web.dispose()
>     }
> ```

Dispose of your SPSite here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/pfe/21)*

**Comment by NikCharlebois** [comment]
Just make sure you review each comment. If you agree with them and implemented the change, you can always click the Done button instead of putting in a custom message.

---

Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/pfe/21#-:-L7dM5XHAzecJ6RwqAxe:busjztq)*

**Comment by RCormier-MSFT** [comment]
Ah, I didn't know that, I'm new to reviewable :)

---

Reviewed 2 of 5 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[PowerShell/Modules/PFE-SharePoint/PFE-SharePoint.psd1, line 21 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7Z9Qc56klD894YAdBG:-L7ZfXW2x-nsvhYenECN:beje5qt) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/PFE-SharePoint.psd1#L21)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

[Picky] Try keeping the tabulation aligned;
</blockquote></details>

I checked in my copy locally, and the tabulation is aligned (sent screenshot via e-mail).  Curious why it's not aligned once it gets in github.  Did  notice a missing comma - so fixed that anyway.

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 2 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7Z9qretUpO8hlwjMM-:-L7ZfohZJgm2r9g3ylWL:bvj2tfc) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L2)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

We should not have a PSScriptInfo block in modules. We should however standardize a comment template at the top of each cmdlet to standardize information about company, description and author. How about something as simple as the following?
<#
        Author:        Roger Cormier
        Company:   Microsoft
       Description: This cmdlet does abcd….
#>
</blockquote></details>

Removed ScriptInfo and standardized using this template

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 44 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZC02b0kBO5SMQyEpO:-L7Zg2beMz3Ldo2yA9q8:b-xwsxy0) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L44)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Instead of adding information in comments, how about we use the HelpMessage attribute?
[parameter(HelpMessage="Represents the SPListBinding", Mandatory=$true,ValueFromPipeline=$True, ValueFromPipelineByPropertyName, ParameterSetName="ListFromPipeline", position=0))]
</blockquote></details>

Implemented HelpMessage attribute, as suggested

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 50 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZCkWgoaUX1hSqUMan:-L7Zg8a0f-p3RxhNSzEW:buq24k0) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L50)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

We may want to remove the Begin block since we are not initializing anything in it. Alternatively, we may want to do an additional check to ensure the piped SPList is not null and throw an error if it is.
</blockquote></details>

Added logic to check whether or not the list is [Microsoft.SharePoint.SPDocumentLibrary] - exit if not.  This way we don't waste our time processing list types that don't support check-in/check-out features.

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1, line 51 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZCkM_PwGbb-OTY8mh:-L7ZmZKNykulNTu8Eawz:bytw5k2) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/Get-CheckedOutFilesInList/Get-CheckedOutFilesInList.psm1#L51)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

> Begin
>     {
>  
>     }
>  
>     Process
>     {
>         $CheckedOutFiles = @{}
>         Write-Verbose "Getting checked out files"
>  
>         foreach( $File in ($List.Items | Where-Object { $_.file.checkoutstatus -ne "None"}))
>         {
>             $CheckedOutFiles.Add($File.url, $File)
>         }
>  
>     }
>  
>     End
>     {
>         Return $CheckedOutFiles
>     }

</blockquote></details>

Same, added logic in begin to make sure we're actually targetting a document library and not something that doesn't support check-in/check-out

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 2 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZCxwuVkSQH8exENb7:-L7ZmffHcPC1o_yXJLM8:bomaush) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L2)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Standardized on the recommended template

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 44 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZDSYInif81EPANOly:-L7Zmi4lZqZjj7Rr7h6X:b-z81rgj) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L44)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Use HelpMessage to provide additional info on what this does.
</blockquote></details>

Implemented

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 47 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZDL_9K0ywsall7Vdr:-L7Zmku6td86jkRoFLSg:b-z81rgj) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L47)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Again, provide HelpMessage to detail what this param is for.
</blockquote></details>

Implemented

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 75 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZDnabh01-z7-tTEwx:-L7Zmq_oa59MB0eT6I4-:byixf33) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L75)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

[Picky] Ensure proper tabulation
</blockquote></details>

Updated indentation

---

*[PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1, line 87 at r1](https://beta.reviewable.io/reviews/microsoft/pfe/21#-L7ZDthXFRvZUPA9_U5x:-L7ZmsMRVAS2G5Eq2WHo:b-z81rgj) ([raw file](https://github.com/microsoft/pfe/blob/8e2f8090c5f5f21567b9600d46c2957372c00193/PowerShell/Modules/PFE-SharePoint/Cmdlets/New-BulkFileCheckIn/New-BulkFileCheckIn.psm1#L87)):*
<details><summary><i>Previously, NikCharlebois (Nik Charlebois) wrote…</i></summary><blockquote>

Dispose of your SPSite here.
</blockquote></details>

Implemented

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/microsoft/pfe/21#-:-L7e4UFLoZbcEMA3OY20:bq1w4vg)*

**Comment by NikCharlebois** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/microsoft/pfe/21#-:-L7e8VioAwJUdx7J7S_n:bnfp4nl)*

**Pull request merged**
